#!/bin/sh
set -x -e
###
# Adding curl
###
apk add --no-cache curl ca-certificates
###
# Installing kops
###
curl -L https://github.com/kubernetes/kops/releases/download/${KOPS_VERSION}/kops-linux-amd64 > /bin/kops 
chmod +x /bin/kops
###
# Installing kubectl
###
curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl > /bin/kubectl
chmod +x /bin/kubectl
###
# Creating kops user
###
addgroup kops
adduser -h /data -s /bin/sh -G kops -D kops
###
# Cleaning image
###
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
apk del curl
